### ISSUE TITLE
Failed to execute script iotprovision-bin

### ISSUE THREAD

**Issue by miroslavpetrov** [microchip-pic-avr-solutions/microchip-iot-developer-guides-for-aws#3]
I am trying to provision a AVR IoT WA board with the provided iot provision tool. I have tried so far on two different computers both running MacOS Catalina.

The output of the tool when using the command _./iotprovision-bin -c aws -m mar --force_ is:

```
    ~/Dow/io/macos  ./iotprovision-bin -c aws -m mar --force

Upgrading debugger firmware...

Currently installed firmware is version 1.20.25
Upgrade candidate firmware is version 1.20.25
Skipping upgrade: Firmware version 1.20.25 is already installed

Loading root CA key
    No key file found, generating new key
    Saving to /Users/miroslavpetrov/.microchip-iot/root-ca.key

Generating self-signed root CA certificate
    Saving to /Users/miroslavpetrov/.microchip-iot/root-ca.crt

Done

Loading signer CA key
    No key file found, generating new key
    Saving to /Users/miroslavpetrov/.microchip-iot/signer-ca.key

Generating signer CA CSR
    Saving to /Users/miroslavpetrov/.microchip-iot/signer-ca.csr

Done

Loading signer CA CSR
    Loading from /Users/miroslavpetrov/.microchip-iot/signer-ca.csr

Loading root CA key
    Loading from /Users/miroslavpetrov/.microchip-iot/root-ca.key

Loading root CA certificate
    Loading from /Users/miroslavpetrov/.microchip-iot/root-ca.crt

Generating signer CA certificate from CSR
    Saving to /Users/miroslavpetrov/.microchip-iot/signer-ca.crt

Done

Programming provisioning firmware
Erasing flash...
Programming flash...
Get provisioner FW version

Provisioning kit with serial number MCHP3349011800000410 using FW version 1.1.2 at port /dev/cu.usbmodem147302

Loading root CA certificate
    Loading from /Users/miroslavpetrov/.microchip-iot/root-ca.crt

Loading signer CA key
    Loading from /Users/miroslavpetrov/.microchip-iot/signer-ca.key

Loading signer CA certificate
    Loading from /Users/miroslavpetrov/.microchip-iot/signer-ca.crt

Erase WINC TLS certificate sector
    Done.

Request device CSR
    Saving to /Users/miroslavpetrov/.microchip-iot/MCHP3349011800000410/device.csr
    Done.

Generating device certificate from CSR
Reading ECC serial number
    Saving to /Users/miroslavpetrov/.microchip-iot/MCHP3349011800000410/device.crt
    Done.


Provisioning device with AWS IoT credentials

Send Signer Certificate
    Done.

Send Device Certificate
    Done.

Transfer certificates to WINC
    Done.

Save thing name in WINC
    Done.

Save AWS endpoint in WINC
AWS endpoint :  a3jfjgk418bjo6.iot.eu-central-1.amazonaws.com
    Done.

Done provisioning thing a014907a50eb66abfabd1d5891780b6e7058bc8e
Traceback (most recent call last):
  File "/Users/joinge/roland/iot-build-pyinstallers/spec/iotprovision-bin.py", line 3, in <module>
  File "iotprovision/iotprovision.py", line 306, in main
  File "iotprovision/provisioner.py", line 320, in aws_provision
  File "iotprovision/aws/aws_mar.py", line 113, in create_device
  File "iotprovision/aws/aws_mar.py", line 35, in register_certificate
  File "botocore/client.py", line 575, in __getattr__
AttributeError: 'IoT' object has no attribute 'register_certificate_without_ca'
[14541] Failed to execute script iotprovision-bin
```

I have been following the tutorial very carefully and I have installed all dependencies as stated.

Any suggestions?

**Comment by johanlofstad** [comment]
Thanks for reporting this issue. This is a bug in the provisioning tool. We've identified the root cause, and it will be fixed in the next version. I do not have a release window for said version, but I've attached a beta release of the Mac version. Please note that this beta release has not been thoroughly tested. Hopefully that should fix your problem.

[iotprovision-bin-mac-1.4.0.114.13-beta.zip](https://github.com/microchip-pic-avr-solutions/microchip-iot-developer-guides-for-aws/files/5509430/iotprovision-bin-mac-1.4.0.114.13-beta.zip)
